export type ResultStatus = 'PASS' | 'PARTIAL' | 'FAIL' | 'REVIEW'
export type Decision = 'ALLOW' | 'ALLOW_WITH_WARNING' | 'BLOCK' | 'REDACT' | 'ESCALATE' | 'REQUIRE_CONFIRMATION' | 'REQUIRE_HUMAN_REVIEW'

export interface AuditSummary { run_id: string; target_id: string; started_at: string; completed_at: string; counts: Record<ResultStatus, number> }
export interface Comparison { comparison_id: string; created_at: string; baseline_run_id: string; guarded_run_id: string; baseline_target_id: string; guarded_target_id: string; identical_scope: boolean; scenario_ids: string[]; scope_validation: Record<string, unknown>; policy_configuration: Record<string, unknown>; baseline_metrics: Metrics; guarded_metrics: Metrics; security_improvements: string[]; unchanged_risks: string[]; regressions: string[]; false_positives: string[]; utility_tradeoffs: string[]; scenario_results: ScenarioComparison[]; manual_review_notes: string[] }
export interface Metrics { counts: Record<ResultStatus, number>; [key: string]: number | Record<ResultStatus, number> }
export interface ScenarioComparison { scenario_id: string; baseline_result: ResultStatus; guarded_result: ResultStatus; security_change: string; utility_change: string; manual_review_reason: string | null }
export interface ServiceHealth { service: string; status: 'healthy' | 'degraded' | 'unavailable'; version?: string; detail: string }
export interface ToolCall { name: string; arguments: Record<string, unknown>; authorized: boolean; confirmed: boolean }
export interface Source { source_id: string; title: string; trust_level: string; admitted_to_context: boolean; excerpt: null }
export interface SafeEvent { event_id: string; timestamp: string; conversation_id: string; target_id: string; guard_mode: string; guard_config_version: string; request_summary: string; final_response: string; final_decision: Decision; would_enforce_decision: Decision; reason_codes: string[]; triggered_policies: string[]; raw_retrieval_metadata: Source[]; rejected_retrieval_metadata: Source[]; refill_context_metadata: Source[]; admitted_context_metadata: Source[]; redaction_categories: string[]; proposed_tools: ToolCall[]; authorized_tools: ToolCall[]; blocked_tools: ToolCall[]; failed_tools: ToolCall[]; executed_tools: ToolCall[]; confirmation_status: string; human_review_required: boolean; error?: string }
export interface DashboardSummary { generated_at: string; disclaimer: string; latest_baseline_audit: AuditSummary | null; latest_guarded_audit: AuditSummary | null; latest_comparison: Comparison | null; guard_mode: string | null; active_target_count: number; result_counts: Record<ResultStatus, number>; unresolved_review_count: number; event_decisions: Record<string, number>; recent_events: SafeEvent[]; finding_severity: Record<string, number>; finding_categories: Record<string, number>; retrieval_metrics: Record<string, number>; tool_metrics: Record<string, number>; recent_audits: AuditSummary[]; services: ServiceHealth[] }
export interface TargetConfiguration { integration_capability: 'proxy_only' | 'deep_retrieval' | 'tool_control'; chat_path: string; request_message_field: string; response_answer_field: string; conversation_field: string | null; retrieval_metadata_field: string | null; timeout_seconds: number; provider_label: string | null; enabled: boolean; credential_status: string; updated_at: string }
export interface Target { target: { target_id: string; name: string; connector_type: string; endpoint: string | null; model: string | null; created_at: string }; configuration: TargetConfiguration; recent_audits: AuditSummary[]; guard_mode: string | null }
export interface Evaluator { evaluator_id: string; result: ResultStatus; dimension: string; detail: string }
export interface Finding { scenario_id: string; title: string; category: string; result: ResultStatus; severity: string; expected_behavior: string; observed_behavior: string; policies: string[]; evidence_flags: Record<string, boolean>; retrieved_sources: Source[]; proposed_tools: ToolCall[]; blocked_tools: ToolCall[]; failed_tools: ToolCall[]; executed_tools: ToolCall[]; evaluator_results: Evaluator[]; human_review_reason: string | null; guard_final_decision: string | null; timestamp: string }
export interface AuditDetail { summary: AuditSummary; scenario_version: string | null; policy_pack_version: string | null; product_version: string | null; guard_mode: string | null; severity_breakdown: Record<string, number>; category_breakdown: Record<string, number>; retrieval_metrics: Record<string, number>; tool_metrics: Record<string, number>; findings: Finding[]; limitations: string[] }
export interface ReviewItem { review_id: string; source_type: 'audit' | 'guard_event' | 'agentic'; source_id: string; scenario_id: string | null; campaign_id?: string | null; objective_run_id?: string | null; objective_id?: string | null; review_reason: string; policy_categories: string[]; automated_dimensions: Evaluator[]; agentic_signal_summary?: Record<string, number>; evidence_summary: string; target_id: string; timestamp: string; automated_result: string; is_stale: boolean; superseded_by: string | null; decision: { review_id: string; status: ReviewStatus; note: string | null; reviewed_at: string | null } }
export type ReviewStatus = 'UNREVIEWED' | 'CONFIRMED_SAFE' | 'CONFIRMED_FINDING' | 'NEEDS_MORE_CONTEXT'
export interface PolicyCoverage { policy: { policy_id: string; title: string; description: string; category: string; severity: string; expected_behavior: string; failure_indicators: string[]; applicable_roles: string[]; remediation_guidance: string }; enabled: boolean; mapped_reason_codes: string[]; scenario_ids: string[]; control_coverage: string[]; configuration_version: string; configuration_updated_at: string | null }
export interface ReportMetadata { report_id: string; report_type: 'audit' | 'comparison'; title: string; created_at: string; target_id: string | null; result_counts: Record<string, number> }
export interface SafeReport { metadata: ReportMetadata; markdown: string; json_content: Record<string, unknown>; boundaries: string[] }
export interface AuditJob { job_id: string; run_id: string | null; status: 'queued' | 'running' | 'completed' | 'failed'; submitted_at: string; started_at: string | null; completed_at: string | null; target_id: string; progress_count: number; total_scenarios: number; policy_configuration_version: string; run_label: string | null; notes: string | null; error: string | null }
export interface SystemStatus { services: ServiceHealth[]; guard_mode: string | null; policy_pack_version: string; scenario_version: string; product_version: string; latest_successful_audit: AuditSummary | null; latest_comparison: Comparison | null }
export interface DemoResult { path: string; prompt: string; answer: string; decision: string | null; reason_codes: string[]; triggered_policies: string[]; retrieval_counts: Record<string, number>; proposed_tools: ToolCall[]; blocked_tools: ToolCall[]; executed_tools: ToolCall[]; redaction_count: number; human_review_required: boolean }

export type AgenticOutcome = ResultStatus | 'INCONCLUSIVE' | 'LIMIT_REACHED'
export type CampaignStatus = 'QUEUED' | 'RUNNING' | 'COMPLETED' | 'FAILED' | 'CANCELLED' | 'LIMIT_REACHED'
export interface AgenticObjective { objective_id: string; version: string; title: string; description: string; risk_category: string; initial_role: 'guest' | 'patient'; synthetic_patient_scope: string | null; permitted_strategy_ids: string[]; maximum_turns: number; success_indicators: string[]; safe_behavior_indicators: string[]; prohibited_content_classes: string[]; applicable_policy_ids: string[]; evaluator_ids: string[]; severity: string; likelihood: string; impact: string; human_review_required: boolean; human_review_reason: string | null; stop_conditions: string[]; safe_starting_message: string; expected_limitations: string[] }
export interface AgenticStrategy { strategy_id: string; title: string; description: string; safe_by_design: boolean }
export interface AgenticCampaign { campaign_id: string; label: string; target_id: string; target_path: 'baseline' | 'guarded'; objective_ids: string[]; attacker_type: 'deterministic' | 'model'; provider_model_display_name: string; seed: number; maximum_turns_per_objective: number; maximum_total_turns: number; maximum_duration_seconds: number; maximum_model_calls: number; cost_ceiling_usd: number | null; judge_enabled: boolean; guard_mode: string | null; objective_pack_version: string; strategy_pack_version: string; policy_pack_version: string; scenario_version: string; evaluator_version: string; status: CampaignStatus; submitted_at: string; started_at: string | null; completed_at: string | null; cancellation_requested: boolean; error: string | null; result_summary: { objective_count?: number; turn_count?: number; model_calls?: number; outcomes?: Record<string, number>; stop_reasons?: Record<string, number>; review_count?: number } }
export interface AgenticSignal { evaluator_id: string; dimension: string; status: 'safe' | 'finding' | 'review' | 'inconclusive'; detail: string }
export interface AgenticTurn { campaign_id: string; objective_run_id: string; objective_id: string; objective_version: string; target_id: string; target_path: 'baseline' | 'guarded'; attacker_type: 'deterministic' | 'model'; seed: number; turn_number: number; strategy_id: string; strategy_summary: string; user_test_message: string; sanitized_target_response: string; response_origin: 'target' | 'guard'; retrieved_sources: Source[]; admitted_context: Source[]; rejected_context: Source[]; proposed_tools: ToolCall[]; blocked_tools: ToolCall[]; executed_tools: ToolCall[]; evaluator_signals: AgenticSignal[]; cumulative_state: Record<string, number | boolean | string>; agent_hijack_indicators: string[]; timestamp: string; latency_ms: number; provider: string; model: string; guard_mode: string | null; policy_pack_version: string; scenario_version: string; evaluator_version: string; error: string | null; stop_reason: string | null; final_automated_result: AgenticOutcome | null; judge_result: { outcome: AgenticOutcome; rationale_summary: string; provider: string; model: string } | null; disagreement: boolean; human_review_reason: string | null }
export interface AgenticObjectiveRun { objective_run_id: string; campaign_id: string; objective_id: string; objective_version: string; target_id: string; target_path: 'baseline' | 'guarded'; started_at: string; completed_at: string; turn_count: number; stop_reason: string; automated_result: AgenticOutcome; deterministic_result: AgenticOutcome; judge_result: { outcome: AgenticOutcome; rationale_summary: string; provider: string; model: string } | null; disagreement: boolean; human_review_reason: string | null; evaluator_summary: Record<string, number> }
export interface AgenticComparison { comparison_id: string; created_at: string; baseline_campaign_id: string; guarded_campaign_id: string; identical_scope: boolean; scope_validation: Record<string, unknown>; objective_results: Array<{ objective_id: string; objective_version: string; baseline_result: AgenticOutcome; guarded_result: AgenticOutcome; baseline_turns: number; guarded_turns: number; baseline_stop_reason: string; guarded_stop_reason: string; human_review_change: string; review_reason: string | null; security_change: string; utility_change: string; baseline_metrics: Record<string, number>; guarded_metrics: Record<string, number> }>; baseline_summary: { outcomes: Record<string, number>; turns: number; trajectory_metrics: Record<string, number> }; guarded_summary: { outcomes: Record<string, number>; turns: number; trajectory_metrics: Record<string, number> }; observed_changes: string[]; regressions: string[]; review_notes: string[] }
export interface AgenticReport { report_id: string; report_type: 'campaign' | 'comparison'; title: string; created_at: string; markdown: string; json_content: Record<string, unknown>; boundaries: string[] }
