import { FormEvent, useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { api } from '../api/client'
import type { AuditJob, PolicyCoverage, Target } from '../api/types'
import { StatusBadge } from '../components/StatusBadge'
import { Card, Disclaimer, ErrorState, Loading, PageHeader } from '../components/UI'

const steps = ['Organization', 'Target type', 'Connector mapping', 'Credentials', 'Capability', 'Policies', 'Connection', 'Initial audit']

export function OnboardingPage() {
  const [step, setStep] = useState(0)
  const [savedTarget, setSavedTarget] = useState<Target | null>(null)
  const [connection, setConnection] = useState<{ status: string; detail: string } | null>(null)
  const [jobs, setJobs] = useState<AuditJob[]>([])
  const queryClient = useQueryClient()
  const policies = useQuery({ queryKey: ['policies'], queryFn: () => api.get<PolicyCoverage[]>('/dashboard/policies') })
  const [form, setForm] = useState({
    organization_name: 'Northstar Digital Health', product_name: 'Northstar Patient Support', environment_label: 'Local evaluation', healthcare_use_case: 'Synthetic patient-support evaluation', technical_contact_name: '', synthetic_data_confirmed: false,
    target_id: 'northstar-demo', name: 'Northstar synthetic target', connector_type: 'demo', endpoint: '', model: '', chat_path: '/chat', request_message_field: 'user_message', response_answer_field: 'answer', conversation_field: 'conversation_id', retrieval_metadata_field: 'retrieved_sources', timeout_seconds: 15, provider_label: 'deterministic-local', credential_env_reference: '', integration_capability: 'deep_retrieval', enabled: true, authorized_target_confirmed: false,
  })
  const [enabledPolicies, setEnabledPolicies] = useState<string[]>([])
  const selectedPolicies = useMemo(() => enabledPolicies.length ? enabledPolicies : policies.data?.map(item => item.policy.policy_id) ?? [], [enabledPolicies, policies.data])
  const save = useMutation({ mutationFn: () => api.post<{ target: Target }>('/dashboard/onboarding', {
    organization: { organization_name: form.organization_name, product_name: form.product_name, environment_label: form.environment_label, healthcare_use_case: form.healthcare_use_case, technical_contact_name: form.technical_contact_name || null, synthetic_data_confirmed: form.synthetic_data_confirmed },
    target: { target_id: form.target_id, name: form.name, connector_type: form.connector_type, endpoint: form.endpoint || null, model: form.model || null, authorized_target_confirmed: form.connector_type === 'demo' || form.authorized_target_confirmed, configuration: { integration_capability: form.integration_capability, chat_path: form.chat_path, request_message_field: form.request_message_field, response_answer_field: form.response_answer_field, conversation_field: form.conversation_field || null, retrieval_metadata_field: form.retrieval_metadata_field || null, timeout_seconds: Number(form.timeout_seconds), provider_label: form.provider_label || null, credential_env_reference: form.credential_env_reference || null, enabled: form.enabled } },
    enabled_policy_ids: selectedPolicies,
  }), onSuccess: data => { setSavedTarget(data.target); queryClient.invalidateQueries(); setStep(6) } })
  const set = (key: string, value: string | boolean | number) => setForm(current => ({ ...current, [key]: value }))
  const next = (event?: FormEvent) => { event?.preventDefault(); if (step === 5) save.mutate(); else setStep(current => Math.min(7, current + 1)) }
  const testConnection = async () => { if (!savedTarget) return; const result = await api.post<{ status: string; detail: string }>(`/dashboard/targets/${savedTarget.target.target_id}/test`); setConnection(result); setStep(7) }
  const runAudit = async (target_id: string) => { const job = await api.post<AuditJob>('/dashboard/audit-jobs', { target_id, run_label: 'Initial onboarding audit', notes: 'Synthetic local onboarding workflow.' }, 60_000); setJobs(current => [...current, job]); queryClient.invalidateQueries() }
  if (policies.isLoading) return <Loading />
  if (policies.error) return <ErrorState error={policies.error} />
  return <>
    <PageHeader eyebrow="Local company setup" title="Connect your healthcare AI product" description="A guided single-tenant demonstration. Credentials remain server-side; use synthetic or explicitly authorized test data only." />
    <Disclaimer />
    <ol className="stepper" aria-label="Onboarding progress">{steps.map((label, index) => <li key={label} className={index === step ? 'active' : index < step ? 'complete' : ''}><button type="button" onClick={() => index <= step && setStep(index)} aria-current={index === step ? 'step' : undefined}><span>{index < step ? '✓' : index + 1}</span>{label}</button></li>)}</ol>
    <Card className="wizard-card"><form onSubmit={next}>
      {step === 0 && <fieldset><legend>Organization profile</legend><div className="form-grid"><label>Organization display name<input required value={form.organization_name} onChange={e => set('organization_name', e.target.value)} /></label><label>Product name<input required value={form.product_name} onChange={e => set('product_name', e.target.value)} /></label><label>Environment label<input required value={form.environment_label} onChange={e => set('environment_label', e.target.value)} /></label><label>Technical contact name <span className="muted">optional</span><input value={form.technical_contact_name} onChange={e => set('technical_contact_name', e.target.value)} /></label><label className="span-2">Healthcare use case<textarea required value={form.healthcare_use_case} onChange={e => set('healthcare_use_case', e.target.value)} /></label><label className="check span-2"><input type="checkbox" checked={form.synthetic_data_confirmed} onChange={e => set('synthetic_data_confirmed', e.target.checked)} /> I confirm this environment will use only synthetic or explicitly authorized test data.</label></div></fieldset>}
      {step === 1 && <fieldset><legend>Choose target type</legend><div className="choice-grid">{[['demo','CareGuard synthetic demo','Offline deterministic target'],['rest','Generic REST chat endpoint','Authorized local HTTP endpoint'],['openai_compatible','OpenAI-compatible connector','Authorized local compatible server']].map(([value,title,description]) => <label className={`choice-card ${form.connector_type === value ? 'selected' : ''}`} key={value}><input type="radio" name="type" checked={form.connector_type === value} onChange={() => { set('connector_type', value); set('integration_capability', value === 'demo' ? 'deep_retrieval' : 'proxy_only'); set('chat_path', value === 'openai_compatible' ? '/v1/chat/completions' : '/chat'); set('authorized_target_confirmed', false) }} /><strong>{title}</strong><span>{description}</span></label>)}</div></fieldset>}
      {step === 2 && <fieldset><legend>Connector mapping</legend><div className="form-grid"><label>Target ID<input required pattern="[A-Za-z0-9._-]+" value={form.target_id} onChange={e => set('target_id', e.target.value)} /></label><label>Target name<input required value={form.name} onChange={e => set('name', e.target.value)} /></label>{form.connector_type !== 'demo' && <><label className="span-2">Authorized local origin<input required placeholder="http://127.0.0.1:8001" value={form.endpoint} onChange={e => set('endpoint', e.target.value)} /></label><p className="field-help span-2">Stage 3 accepts only exact local synthetic origins on ports 8001 or 8002. Paths, query strings, embedded credentials, redirects, and public hosts are rejected.</p><label className="check span-2"><input type="checkbox" checked={form.authorized_target_confirmed} onChange={e => set('authorized_target_confirmed', e.target.checked)} /> I confirm that I own or am explicitly authorized to test this local synthetic target.</label></>}<label>Chat path<input value={form.chat_path} onChange={e => set('chat_path', e.target.value)} /></label><label>Timeout (seconds)<input type="number" min="1" max="60" value={form.timeout_seconds} onChange={e => set('timeout_seconds', Number(e.target.value))} /></label><label>Request message field<input value={form.request_message_field} onChange={e => set('request_message_field', e.target.value)} /></label><label>Response answer field<input value={form.response_answer_field} onChange={e => set('response_answer_field', e.target.value)} /></label><label>Conversation field<input value={form.conversation_field} onChange={e => set('conversation_field', e.target.value)} /></label><label>Retrieval metadata field<input value={form.retrieval_metadata_field} onChange={e => set('retrieval_metadata_field', e.target.value)} /></label></div></fieldset>}
      {step === 3 && <fieldset><legend>Server-side credential reference</legend><div className="alert alert-info"><strong>No secret values are accepted here.</strong><span>Select only the name of a server-side environment reference. CareGuard never returns its value.</span></div><label>Credential environment reference<select value={form.credential_env_reference} onChange={e => set('credential_env_reference', e.target.value)}><option value="">None — default local workflow</option><option value="OPENAI_COMPATIBLE_API_KEY">OPENAI_COMPATIBLE_API_KEY</option></select></label><p className="field-help">Configure the value in <code>.env</code> or deployment configuration, then restart services. The browser receives only configured, unavailable, or not configured.</p></fieldset>}
      {step === 4 && <fieldset><legend>Integration capability</legend><div className="choice-grid">{[['proxy_only','Proxy only','Request, surfaced response, and visible tool metadata. No hidden context filtering.'],['deep_retrieval','Deep retrieval','Authorized retrieval/generation hooks allow context admission and refill.'],['tool_control','Tool control','Proposals are authorized and confirmed before simulated execution.']].map(([value,title,description]) => <label className={`choice-card ${form.integration_capability === value ? 'selected' : ''}`} key={value}><input type="radio" name="capability" checked={form.integration_capability === value} onChange={() => set('integration_capability', value)} /><strong>{title}</strong><span>{description}</span></label>)}</div></fieldset>}
      {step === 5 && <fieldset><legend>Healthcare policy selection</legend><p className="field-help">Policy IDs remain immutable. This local selection is validated and versioned by the backend.</p><div className="policy-select">{policies.data!.map(item => <label className="check" key={item.policy.policy_id}><input type="checkbox" checked={selectedPolicies.includes(item.policy.policy_id)} onChange={e => setEnabledPolicies(e.target.checked ? [...new Set([...selectedPolicies, item.policy.policy_id])] : selectedPolicies.filter(id => id !== item.policy.policy_id))} /><span><strong>{item.policy.policy_id}</strong> {item.policy.title}<small>{item.policy.category}</small></span></label>)}</div></fieldset>}
      {step === 6 && <fieldset><legend>Harmless connection test</legend>{savedTarget && <div className="connection-panel"><div><strong>{savedTarget.target.name}</strong><span>{savedTarget.target.connector_type} · {savedTarget.configuration.integration_capability}</span></div>{connection ? <StatusBadge value={connection.status} /> : <button type="button" className="button button-primary" onClick={testConnection}>Test connection</button>}</div>}{connection && <div className="alert alert-info"><strong>Sanitized result</strong><span>{connection.detail}</span></div>}</fieldset>}
      {step === 7 && <fieldset><legend>Initial audit</legend><p>Launch the fixed synthetic suite. Jobs complete locally and preserve every REVIEW outcome.</p><div className="initial-actions"><button type="button" className="button button-primary" onClick={() => runAudit(savedTarget?.target.target_id ?? form.target_id)}>Run target audit</button><button type="button" className="button" onClick={() => runAudit('demo-guarded')}>Run guarded reference audit</button></div>{jobs.map(job => <div className="job-result" key={job.job_id}><StatusBadge value={job.status} /><span>{job.target_id} · {job.progress_count}/{job.total_scenarios} scenarios</span>{job.run_id && <Link to={`/audits/${job.run_id}`}>Open results →</Link>}</div>)}</fieldset>}
      {save.error && <div className="alert alert-error" role="alert">{save.error.message}</div>}
      <div className="wizard-actions">{step > 0 && step < 6 && <button type="button" className="button" onClick={() => setStep(current => current - 1)}>Back</button>}{step < 6 && <button className="button button-primary" disabled={(step === 0 && !form.synthetic_data_confirmed) || (step === 2 && form.connector_type !== 'demo' && !form.authorized_target_confirmed) || save.isPending}>{step === 5 ? save.isPending ? 'Saving…' : 'Save configuration' : 'Continue'}</button>}{step === 7 && <Link className="button" to="/">Finish onboarding</Link>}</div>
    </form></Card>
  </>
}
